"""initial schema

Revision ID: 4f6d183ff88d
Revises: 
Create Date: 2026-07-17 06:27:45.477851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f6d183ff88d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_bars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('open', sa.Float(), nullable=True),
    sa.Column('high', sa.Float(), nullable=True),
    sa.Column('low', sa.Float(), nullable=True),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_price_bars'))
    )
    with op.batch_alter_table('price_bars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_bars_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_bars_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_bars_ticker'), ['ticker'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('backtest_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('ticker_a', sa.String(), nullable=False),
    sa.Column('ticker_b', sa.String(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('equity_curve', sa.JSON(), nullable=True),
    sa.Column('error', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_backtest_results_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_backtest_results'))
    )
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_backtest_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_backtest_results_task_id'), ['task_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_backtest_results_user_id'), ['user_id'], unique=False)

    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ticker_a', sa.String(), nullable=False),
    sa.Column('ticker_b', sa.String(), nullable=False),
    sa.Column('direction', sa.String(), nullable=True),
    sa.Column('hedge_ratio', sa.Float(), nullable=True),
    sa.Column('entry_z', sa.Float(), nullable=True),
    sa.Column('exit_z', sa.Float(), nullable=True),
    sa.Column('entry_price_a', sa.Float(), nullable=True),
    sa.Column('entry_price_b', sa.Float(), nullable=True),
    sa.Column('exit_price_a', sa.Float(), nullable=True),
    sa.Column('exit_price_b', sa.Float(), nullable=True),
    sa.Column('capital_allocated', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pnl', sa.Float(), nullable=True),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_paper_trades_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_paper_trades'))
    )
    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_paper_trades_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_paper_trades_user_id'), ['user_id'], unique=False)

    op.create_table('research_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('cells', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_research_sessions_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_research_sessions'))
    )
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_sessions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_sessions_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('research_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_research_sessions_id'))

    op.drop_table('research_sessions')
    with op.batch_alter_table('paper_trades', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_paper_trades_user_id'))
        batch_op.drop_index(batch_op.f('ix_paper_trades_id'))

    op.drop_table('paper_trades')
    with op.batch_alter_table('backtest_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_backtest_results_user_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_results_task_id'))
        batch_op.drop_index(batch_op.f('ix_backtest_results_id'))

    op.drop_table('backtest_results')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('price_bars', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_bars_ticker'))
        batch_op.drop_index(batch_op.f('ix_price_bars_id'))
        batch_op.drop_index(batch_op.f('ix_price_bars_date'))

    op.drop_table('price_bars')
    # ### end Alembic commands ###
