"""add google oauth fields to users

Revision ID: 6e64f54d8f91
Revises: 4f6d183ff88d
Create Date: 2026-07-18 04:25:22.781235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e64f54d8f91'
down_revision: Union[str, Sequence[str], None] = '4f6d183ff88d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default ensures any existing rows get backfilled with 'password'
        # (their real auth method) instead of failing the NOT NULL constraint.
        batch_op.add_column(sa.Column('auth_provider', sa.String(), nullable=False, server_default='password'))
        batch_op.add_column(sa.Column('google_sub', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('picture_url', sa.String(), nullable=True))
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_users_google_sub'), ['google_sub'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_google_sub'))
        batch_op.alter_column('hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('picture_url')
        batch_op.drop_column('name')
        batch_op.drop_column('google_sub')
        batch_op.drop_column('auth_provider')

    # ### end Alembic commands ###
